# Generated by Django 5.2.10 on 2026-02-13 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_manage', '0001_initial'),
        ('player_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending manager approval'), (2, 'Pending player confirmation'), (3, 'Pending_pay'), (4, 'Completed'), (5, 'Canceled'), (6, 'REJECT'), (7, 'No-Show'), (8, 'Disputed'), (9, 'Expired')])),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('change_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
            ],
            options={
                'verbose_name': 'Booking Status History',
                'verbose_name_plural': 'Booking Status Histories',
                'db_table': 'booking_status_history',
                'ordering': ['-change_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('old_date', models.DateField()),
                ('old_start_time', models.TimeField()),
                ('old_end_time', models.TimeField()),
                ('new_date', models.DateField()),
                ('new_start_time', models.TimeField()),
                ('new_end_time', models.TimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'accept'), (3, 'reject')], default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_booking_notifications', to='dashboard_manage.club')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Notification',
                'verbose_name_plural': 'Booking Notifications',
                'db_table': 'booking_notifications',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['send_to'], name='booking_not_send_to_2964f5_idx')],
            },
        ),
    ]
