# Generated by Django 5.2.10 on 2026-01-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0001_initial'),
        ('dashboard_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingnotification',
            name='send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_booking_notifications', to='dashboard_manage.club'),
        ),
    ]
