# Generated by Django 5.2.10 on 2026-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار تاكيد المدير'), (2, 'بانتظار تاكيد اللاعب'), (3, 'بانتظار الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'لم يحضر'), (8, 'مشكلة'), (9, 'انتهت صلاحيته')]),
        ),
    ]
