# Generated by Django 5.2.10 on 2026-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0002_alter_bookingnotification_send_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingnotification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookingstatushistory',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='bookingstatushistory',
            name='old_status',
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending_manager'), (2, 'Pending_player'), (3, 'Pending_pay'), (4, 'Completed'), (5, 'Canceled'), (6, 'reject')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingnotification',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'accept'), (3, 'reject')], default=1),
        ),
    ]
