# Generated by Django 5.2.10 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0003_alter_bookingstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار تاكيد المدير'), (2, 'بانتظار تاكيد اللاعب'), (3, 'بانتظار الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'لم يحضر'), (8, 'مشكلة'), (9, 'انتهت صلاحيته'), (10, 'فترة مغلقة'), (11, 'الدفع عبر التطبيق')]),
        ),
    ]
