# Generated by Django 5.2.10 on 2026-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0003_remove_bookingnotification_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending_manager'), (2, 'Pending_player'), (3, 'Pending_pay'), (4, 'Completed'), (5, 'Canceled'), (6, 'Reject'), (7, 'No-Show'), (8, 'Disputed'), (9, 'Expired')]),
        ),
    ]
