# Generated by Django 5.2.10 on 2026-05-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0004_alter_bookingstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatushistory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار_تأكيد_النادي'), (2, 'وقت_مقترح_جديد'), (3, 'بانتظار_تكملة_الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'متغيب'), (8, 'مشكلة'), (9, 'انتهت_صلاحيته'), (10, 'فترة_مغلقة'), (11, 'بانتظار_الدفع')]),
        ),
    ]
