# Generated by Django 5.2.10 on 2026-05-11 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_booking', '0006_alter_bookingstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
