# Generated by Django 5.2.10 on 2026-05-21 19:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'بانتظار_تأكيد_النادي'), (2, 'وقت_مقترح_جديد'), (3, 'بانتظار_تكملة_الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'متغيب'), (8, 'مشكلة'), (9, 'انتهت_صلاحيته'), (10, 'فترة_مغلقة'), (11, 'بانتظار_الدفع'), (12, 'بانتظار_تأكبد_الدفع')], default=1)),
                ('payment_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'لاحقا'), (6, 'دفعة مقدمة'), (3, 'اونلاين'), (4, 'نقدا'), (5, 'غير معروف'), (2, 'دفعة مقدمة')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_owner', models.TextField(blank=True)),
                ('note_admin', models.TextField(blank=True)),
                ('by_owner', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with "09" and contain exactly 10 digits (e.g., 0912345678).', regex='^09\\d{8}$')])),
                ('is_challenge', models.BooleanField(default=False)),
                ('owner_reminded', models.BooleanField(default=False)),
                ('rate_notified', models.BooleanField(default=False)),
                ('rate_done', models.BooleanField(default=False)),
                ('pay_reminded', models.BooleanField(default=False)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_manage.club')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.pitch')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment')),
                ('equipment_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='dashboard_manage.club')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='player_booking.coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='player_booking.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player_id', 'created_at'], name='bookings_player__d1cda3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'date'], name='bookings_pitch_i_1e5660_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'date', 'start_time'], name='bookings_pitch_i_d9e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player'], name='bookings_player__c5003c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', 'created_at', 'status'], name='booking_player_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('is_challenge', True)), fields=['is_challenge', 'status', 'created_at'], name='booking_challenge_pending'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['club'], name='reviews_club_id_949c97_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='reviews_booking_012755_idx'),
        ),
    ]
