# Generated by Django 5.2.10 on 2026-02-13 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending manager approval'), (2, 'Pending player confirmation'), (3, 'Pending_pay'), (4, 'Completed'), (5, 'Canceled'), (6, 'REJECT'), (7, 'No-Show'), (8, 'Disputed'), (9, 'Expired')], default=1)),
                ('payment_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Later'), (2, 'Deposit'), (3, 'Online'), (4, 'Cash'), (5, 'Unknown')], default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_owner', models.TextField(blank=True)),
                ('note_admin', models.TextField(blank=True)),
                ('by_owner', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with "09" and contain exactly 10 digits (e.g., 0912345678).', regex='^09\\d{8}$')])),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.pitch')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'date'], name='bookings_pitch_i_1e5660_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pitch', 'date', 'start_time'], name='bookings_pitch_i_d9e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player'], name='bookings_player__c5003c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['club'], name='reviews_club_id_949c97_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='reviews_booking_012755_idx'),
        ),
    ]
