# Generated by Django 5.2.10 on 2026-02-13 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingequipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
