# Generated by Django 5.2.10 on 2026-02-05 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0002_alter_booking_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='note_owner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Later'), (2, 'Deposit'), (3, 'Online'), (4, 'Cash'), (5, 'Unknown')], default=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with "09" and contain exactly 10 digits (e.g., 0912345678).', regex='^09\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending_manager'), (2, 'Pending_player'), (3, 'Pending_pay'), (4, 'Completed'), (5, 'Canceled'), (6, 'Reject'), (7, 'No-Show'), (8, 'Disputed'), (9, 'Expired')], default=1),
        ),
    ]
