# Generated by Django 5.2.10 on 2026-02-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0002_alter_bookingequipment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingequipment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookingequipment',
            name='start_time',
        ),
    ]
