# Generated by Django 5.2.10 on 2026-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0002_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'لاحقاً'), (2, 'دفعة مقدمة'), (3, 'اونلاين'), (4, 'نقداً'), (5, 'غير معروف'), (6, 'دفعة مقدمة عبر الدفع الإلكتروني')], default=5),
        ),
    ]
