# Generated by Django 5.2.10 on 2026-02-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0003_booking_by_owner_booking_deposit_booking_note_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending manager approval'), (2, 'Pending player confirmation'), (3, 'Pending_pay'), (4, 'Completed'), (5, 'Canceled'), (6, 'Rejected'), (7, 'No-Show'), (8, 'Disputed'), (9, 'Expired')], default=1),
        ),
    ]
