# Generated by Django 5.2.10 on 2026-02-20 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0005_clubequipment_price_alter_clubequipment_equipment'),
        ('player_booking', '0003_remove_bookingequipment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingequipment',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
