# Generated by Django 5.2.10 on 2026-02-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0006_alter_clubequipment_equipment_and_more'),
        ('player_booking', '0004_remove_bookingequipment_name_booking_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_manage.club'),
        ),
    ]
