# Generated by Django 5.2.10 on 2026-02-21 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0006_alter_clubequipment_equipment_and_more'),
        ('player_booking', '0005_booking_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingequipment',
            name='equipment_def',
            field=models.ForeignKey(default='0930239f-2567-462e-8b5c-2119c2c53500', on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment'),
        ),
        migrations.AlterField(
            model_name='bookingequipment',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
