# Generated by Django 5.2.10 on 2026-03-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0006_bookingequipment_equipment_def_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
