# Generated by Django 5.2.10 on 2026-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0007_booking_is_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'لاحقا'), (2, 'دفعة مقدمة'), (3, 'اونلاين'), (4, 'نقدا'), (5, 'غير معروف')], default=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار تاكيد المدير'), (2, 'بانتظار تاكيد اللاعب'), (3, 'بانتظار الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'لم يحضر'), (8, 'مشكلة'), (9, 'انتهت صلاحيته')], default=1),
        ),
    ]
