# Generated by Django 5.2.10 on 2026-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0008_alter_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار تاكيد المدير'), (2, 'بانتظار تاكيد اللاعب'), (3, 'بانتظار الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'لم يحضر'), (8, 'مشكلة'), (9, 'انتهت صلاحيته'), (10, 'فترة مغلقة')], default=1),
        ),
    ]
