# Generated by Django 5.2.10 on 2026-05-02 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0018_bookingnumstatistics_pay_num_clubdeposit'),
        ('player_booking', '0010_coupon_booking_coupon_couponusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار تاكيد المدير'), (2, 'بانتظار تاكيد اللاعب'), (3, 'بانتظار الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'لم يحضر'), (8, 'مشكلة'), (9, 'انتهت صلاحيته'), (10, 'فترة مغلقة'), (11, 'الدفع عبر التطبيق')], default=1),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player_id', 'created_at'], name='bookings_player__d1cda3_idx'),
        ),
    ]
