# Generated by Django 5.2.10 on 2026-04-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0010_coupon_booking_coupon_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
