# Generated by Django 5.2.10 on 2026-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0011_booking_owner_reminded'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate_notified',
            field=models.BooleanField(default=False),
        ),
    ]
