# Generated by Django 5.2.10 on 2026-05-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0011_alter_booking_status_and_more'),
        ('player_booking', '0012_booking_rate_notified'),
    ]

    operations = [
    ]
