# Generated by Django 5.2.10 on 2026-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0014_alter_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_reminded',
            field=models.BooleanField(default=False),
        ),
    ]
