# Generated by Django 5.2.10 on 2026-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0015_booking_pay_reminded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'لاحقا'), (6, 'دفعة مقدمة'), (3, 'اونلاين'), (4, 'نقدا'), (5, 'غير معروف'), (2, 'دفعة مقدمة')], default=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار_تأكيد_النادي'), (2, 'وقت_مقترح_جديد'), (3, 'بانتظار_تكملة_الدفع'), (4, 'مكتمل'), (5, 'ملغى'), (6, 'مرفوض'), (7, 'متغيب'), (8, 'مشكلة'), (9, 'انتهت_صلاحيته'), (10, 'فترة_مغلقة'), (11, 'بانتظار_الدفع'), (12, 'بانتظار_تأكبد_الدفع')], default=1),
        ),
    ]
