# Generated by Django 5.2.10 on 2026-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0016_alter_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rate_done',
            field=models.BooleanField(default=False),
        ),
    ]
