# Generated by Django 5.2.10 on 2026-05-13 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0018_bookingnumstatistics_pay_num_clubdeposit'),
        ('player_booking', '0017_booking_rate_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['player', 'created_at', 'status'], name='booking_player_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('is_challenge', True)), fields=['is_challenge', 'status', 'created_at'], name='booking_challenge_pending'),
        ),
    ]
