# Generated by Django 5.2.10 on 2026-05-21 19:32

import core.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with "09" and contain exactly 10 digits (e.g., 0912345678).', regex='^09\\d{8}$')], verbose_name='Phone Number')),
                ('image', models.ImageField(blank=True, default='users/images/Default/avatar.png', upload_to=core.utils.user_image_upload_path, verbose_name='Profile Image')),
                ('image_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Image Updated At')),
                ('role', models.PositiveSmallIntegerField(default=1, verbose_name='Role')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('foot_preference', models.SmallIntegerField(choices=[(1, 'يسار'), (2, 'يمين'), (3, 'كلاهما')])),
                ('booking_time', models.PositiveIntegerField(default=0, verbose_name='Booking Time')),
                ('cancel_time', models.PositiveIntegerField(default=0, verbose_name='Cancel Time')),
                ('no_show_time', models.PositiveIntegerField(default=0, verbose_name='No show Time')),
                ('disputed_time', models.PositiveIntegerField(default=0, verbose_name='Disputed Time')),
                ('expired_time', models.PositiveIntegerField(default=0)),
                ('challenge_time', models.PositiveIntegerField(default=0, verbose_name='Booking Time')),
                ('challenge_wins', models.PositiveBigIntegerField(default=0)),
                ('challenge_losses', models.PositiveBigIntegerField(default=0)),
                ('challenge_draw', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('governorate', models.PositiveSmallIntegerField(choices=[(1, 'دمشق'), (2, 'ريف دمشق'), (3, 'حمص'), (4, 'اللاذقية'), (5, 'طرطوس')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=20)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('build_number', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('download_url', models.URLField()),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('app_type', 'platform', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=100)),
                ('helper_id', models.CharField(max_length=100)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sended_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True, verbose_name='FCM Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'db_table': 'user_devices',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
    ]
