# Generated by Django 5.2.10 on 2026-01-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
