# Generated by Django 5.2.10 on 2026-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='helper_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
