# Generated by Django 5.2.10 on 2026-04-06 10:56

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_foot_preference_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.user_image_upload_path, verbose_name='Profile Image'),
        ),
    ]
