# Generated by Django 5.2.10 on 2026-04-06 12:39

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/images/Default/avatar.png', null=True, upload_to=core.utils.user_image_upload_path, verbose_name='Profile Image'),
        ),
    ]
