# Generated by Django 5.2.10 on 2026-04-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Image Updated At'),
        ),
    ]
