# Generated by Django 5.2.10 on 2026-04-21 21:05

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_image_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/images/Default/avatar.png', upload_to=core.utils.user_image_upload_path, verbose_name='Profile Image'),
        ),
    ]
