# Generated by Django 5.2.10 on 2026-04-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_image'),
        ('core', '0010_note'),
    ]

    operations = [
    ]
