# Generated by Django 5.2.10 on 2026-04-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_0010_alter_user_image_0010_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Booking Time'),
        ),
        migrations.AddField(
            model_name='user',
            name='disputed_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Disputed Time'),
        ),
        migrations.AddField(
            model_name='user',
            name='no_show_time',
            field=models.PositiveIntegerField(default=0, verbose_name='No show Time'),
        ),
    ]
