# Generated by Django 5.2.10 on 2026-04-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_challenge_time_user_disputed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sended_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
