# Generated by Django 5.2.10 on 2026-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_wins',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
