# Generated by Django 5.2.10 on 2026-05-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_challenge_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=20)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('build_number', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('download_url', models.URLField()),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('app_type', 'platform', 'version')},
            },
        ),
    ]
