# Generated by Django 5.2.10 on 2026-05-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
