# Generated by Django 5.2.10 on 2026-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_appversion_is_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='challenge_draw',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='challenge_losses',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
