# Generated by Django 5.2.10 on 2026-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_challenge_draw_user_challenge_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expired_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
