# Generated by Django 5.2.10 on 2026-05-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='governorate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'دمشق'), (2, 'ريف دمشق'), (3, 'حمص'), (4, 'اللاذقية'), (5, 'طرطوس')]),
        ),
    ]
