# Generated by Django 5.2.10 on 2026-01-24 11:59

import core.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('post_type', models.SmallIntegerField(choices=[(1, 'Team Seeking Player'), (2, 'Player Seeking Team')])),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruitment Post',
                'verbose_name_plural': 'Recruitment Posts',
                'db_table': 'recruitment_posts',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('time', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
                ('total_wins', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_losses', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_draw', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_canceled', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_scored', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_conceded', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('clean_sheet', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_to_score', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('challenge_mode', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recruitment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_team.recruitmentpost')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_team.team')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'requests',
            },
        ),
        migrations.AddField(
            model_name='recruitmentpost',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_team.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'out'), (3, 'Inactive')], default=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('leave_at', models.DateTimeField(blank=True, null=True)),
                ('is_captain', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_team.team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['captain', 'is_active'], name='teams_captain_5a2c68_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['recruitment_post'], name='requests_recruit_602926_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['team'], name='requests_team_id_ba3209_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['player'], name='requests_player__43a650_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentpost',
            index=models.Index(fields=['is_open'], name='recruitment_is_open_f0e4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentpost',
            index=models.Index(fields=['is_open', 'team'], name='recruitment_is_open_ff6431_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentpost',
            index=models.Index(fields=['is_open', 'player'], name='recruitment_is_open_2bafab_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team'], name='team_member_team_id_db77a4_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['player'], name='team_member_player__42f8af_idx'),
        ),
    ]
