# Generated by Django 5.2.10 on 2026-03-07 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'status'], name='team_member_team_id_62e01f_idx'),
        ),
    ]
