# Generated by Django 5.2.10 on 2026-02-01 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='recruitment_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_team.recruitmentpost'),
        ),
    ]
