# Generated by Django 5.2.10 on 2026-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0002_teammember_team_member_team_id_62e01f_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'نشط'), (2, 'مغادر'), (3, 'غير نشط')], default=1),
        ),
    ]
