# Generated by Django 5.2.10 on 2026-02-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0002_alter_request_recruitment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
            preserve_default=False,
        ),
    ]
