# Generated by Django 5.2.10 on 2026-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0003_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentpost',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'هجوم'), (2, 'وسط'), (3, 'دفاع'), (4, 'حارس')]),
        ),
    ]
