# Generated by Django 5.2.10 on 2026-05-13 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0003_alter_teammember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['player', 'status', 'team'], name='tm_player_active'),
        ),
    ]
