# Generated by Django 5.2.10 on 2026-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0004_teammember_tm_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='governorate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'دمشق'), (2, 'ريف دمشق'), (3, 'حمص'), (4, 'اللاذقية'), (5, 'طرطوس')], default=1),
        ),
    ]
