# Generated by Django 5.2.10 on 2026-02-03 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0005_request_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['player', 'status'], name='team_member_player__fc5d63_idx'),
        ),
    ]
