# Generated by Django 5.2.10 on 2026-02-07 20:35

import core.utils
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0006_alter_team_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
            ],
        ),
    ]
