# Generated by Django 5.2.10 on 2026-02-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0007_teamimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamImages',
            new_name='TeamImage',
        ),
    ]
