# Generated by Django 5.2.10 on 2026-02-07 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_team', '0010_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='player_team.teamimage'),
            preserve_default=False,
        ),
    ]
