# Generated by Django 5.2.10 on 2026-05-21 19:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_manage', '0001_initial'),
        ('player_booking', '0001_initial'),
        ('player_team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_team', models.PositiveSmallIntegerField(default=0)),
                ('result_challenged_team', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'بانتظار_الفريق_المنافس'), (2, 'بانتظار_تأكيد_النادي'), (3, 'بانتظار_تكملة_الدفع'), (4, 'مكتمل'), (5, 'مرفوض'), (6, 'ملغى'), (7, 'متغيب'), (8, 'مشكلة_في_النتيجة'), (9, 'مشكلة'), (10, 'انتهت_صلاحيته'), (11, 'بانتظار_الدفع'), (12, 'بانتظار_تأكبد_الدفع')], default=1)),
                ('note_admin', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('score_notified', models.BooleanField(default=False)),
                ('score_finalized', models.BooleanField(default=False)),
                ('deposit_percent', models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('challenged_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_team.team')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.pitch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_challenge', to='player_team.team')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_competition.challenge')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengePlayerBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score_done', models.BooleanField(default=False)),
                ('rate_done', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_competition.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_team', models.PositiveSmallIntegerField()),
                ('result_challenged_team', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submissions', to='player_competition.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_submissions',
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['booking'], name='challenges_booking_874579_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['date'], name='challenges_date_49bf55_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['team'], name='challenges_team_id_97fd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenged_team'], name='challenges_challen_f44138_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', 'created_at'], name='challenges_status_7602d2_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(condition=models.Q(('booking__isnull', True)), fields=['status', 'created_at'], name='challenge_pending_null'),
        ),
        migrations.AddIndex(
            model_name='challengeplayerbooking',
            index=models.Index(fields=['booking_id', 'player_id'], name='player_comp_booking_00a03e_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeplayerbooking',
            index=models.Index(fields=['player_id', 'booking_id'], name='cpb_player_booking'),
        ),
        migrations.AddConstraint(
            model_name='challengeplayerbooking',
            constraint=models.UniqueConstraint(fields=('challenge', 'player'), name='unique_player_per_challenge'),
        ),
        migrations.AddConstraint(
            model_name='scoresubmission',
            constraint=models.UniqueConstraint(fields=('challenge', 'player'), name='unique_score_per_player_per_challenge'),
        ),
    ]
