# Generated by Django 5.2.10 on 2026-01-24 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_manage', '0001_initial'),
        ('player_booking', '0001_initial'),
        ('player_team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_team', models.PositiveSmallIntegerField()),
                ('result_challenged_team', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Canceled')], default=1)),
                ('note_admin', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
                ('challenged_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_team.team')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.pitch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_challenge', to='player_team.team')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'db_table': 'challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='challenges_booking_874579_idx'), models.Index(fields=['date'], name='challenges_date_49bf55_idx'), models.Index(fields=['team'], name='challenges_team_id_97fd0a_idx'), models.Index(fields=['challenged_team'], name='challenges_challen_f44138_idx')],
            },
        ),
    ]
