# Generated by Django 5.2.10 on 2026-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending-Team'), (2, 'Pending-Owner'), (3, 'Pending-Pay'), (4, 'Accepted'), (5, 'Rejected'), (6, 'Canceled')], default=1),
        ),
    ]
