# Generated by Django 5.2.10 on 2026-03-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0011_bookingduration'),
        ('player_competition', '0002_remove_challenge_created_by_alter_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='club',
            field=models.ForeignKey(default='b3dccb49-7b53-4cea-8532-b54f95e1005e', on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='result_challenged_team',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='result_team',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
