# Generated by Django 5.2.10 on 2026-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0003_challenge_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار الفريق'), (2, 'بانتظار المالك'), (3, 'بانتظار الدفع'), (4, 'مقبول'), (5, 'مرفوض'), (6, 'ملغى')], default=1),
        ),
    ]
