# Generated by Django 5.2.10 on 2026-04-17 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_booking', '0009_alter_booking_status'),
        ('player_competition', '0004_alter_challenge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengePlayerBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_booking.booking')),
            ],
        ),
    ]
