# Generated by Django 5.2.10 on 2026-04-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0005_challengeplayerbooking'),
        ('player_team', '0003_alter_teammember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeplayerbooking',
            name='challenge',
            field=models.ForeignKey(default='e6c4369f-0ade-43a6-925e-cfe728d90f6b', on_delete=django.db.models.deletion.CASCADE, to='player_competition.challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengeplayerbooking',
            name='player',
            field=models.ForeignKey(default='e6c4369f-0ade-43a6-925e-cfe728d90f6b', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengeplayerbooking',
            name='team',
            field=models.ForeignKey(default='e6c4369f-0ade-43a6-925e-cfe728d90f6b', on_delete=django.db.models.deletion.CASCADE, to='player_team.team'),
            preserve_default=False,
        ),
    ]
