# Generated by Django 5.2.10 on 2026-04-21 16:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0017_alter_clubstaff_club'),
        ('player_booking', '0009_alter_booking_status'),
        ('player_competition', '0006_challengeplayerbooking_challenge_and_more'),
        ('player_team', '0003_alter_teammember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='challengeplayerbooking',
            constraint=models.UniqueConstraint(fields=('challenge', 'player'), name='unique_player_per_challenge'),
        ),
        migrations.AddField(
            model_name='challengeequipment',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_competition.challenge'),
        ),
        migrations.AddField(
            model_name='challengeequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment'),
        ),
    ]
