# Generated by Django 5.2.10 on 2026-05-02 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0007_challengeequipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_team', models.PositiveSmallIntegerField()),
                ('result_challenged_team', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submissions', to='player_competition.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_submissions',
                'constraints': [models.UniqueConstraint(fields=('challenge', 'player'), name='unique_score_per_player_per_challenge')],
            },
        ),
    ]
