# Generated by Django 5.2.10 on 2026-05-02 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0018_bookingnumstatistics_pay_num_clubdeposit'),
        ('player_booking', '0011_alter_booking_status_and_more'),
        ('player_competition', '0007_challengeequipment_and_more'),
        ('player_team', '0003_alter_teammember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار الفريق'), (2, 'بانتظار المالك'), (3, 'بانتظار الدفع'), (4, 'مقبول'), (5, 'مرفوض'), (6, 'ملغى'), (7, 'لم يحضر'), (8, 'مشكلة في النتيجة'), (9, 'مشكلة'), (10, 'انتهت صلاحيته'), (11, 'الدفع عبر التطبيق')], default=1),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', 'created_at'], name='challenges_status_7602d2_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeplayerbooking',
            index=models.Index(fields=['booking_id', 'player_id'], name='player_comp_booking_00a03e_idx'),
        ),
    ]
