# Generated by Django 5.2.10 on 2026-05-02 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0008_alter_challenge_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
