# Generated by Django 5.2.10 on 2026-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0008_scoresubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='score_notified',
            field=models.BooleanField(default=False),
        ),
    ]
