# Generated by Django 5.2.10 on 2026-05-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0009_challenge_deposit_percent'),
        ('player_competition', '0009_challenge_score_notified'),
    ]

    operations = [
    ]
