# Generated by Django 5.2.10 on 2026-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0011_alter_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='score_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
