# Generated by Django 5.2.10 on 2026-05-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0012_challenge_score_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بانتظار_الفريق_المنافس'), (2, 'بانتظار_تأكيد_النادي'), (3, 'بانتظار_تكملة_الدفع'), (4, 'مكتمل'), (5, 'مرفوض'), (6, 'ملغى'), (7, 'متغيب'), (8, 'مشكلة_في_النتيجة'), (9, 'مشكلة'), (10, 'انتهت_صلاحيته'), (11, 'بانتظار_الدفع'), (12, 'بانتظار_تأكبد_الدفع')], default=1),
        ),
    ]
