# Generated by Django 5.2.10 on 2026-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_competition', '0013_alter_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeplayerbooking',
            name='rate_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challengeplayerbooking',
            name='score_done',
            field=models.BooleanField(default=False),
        ),
    ]
