# Generated by Django 5.2.10 on 2026-05-13 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0018_bookingnumstatistics_pay_num_clubdeposit'),
        ('player_booking', '0018_booking_booking_player_created_and_more'),
        ('player_competition', '0014_challengeplayerbooking_rate_done_and_more'),
        ('player_team', '0004_teammember_tm_player_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(condition=models.Q(('booking__isnull', True)), fields=['status', 'created_at'], name='challenge_pending_null'),
        ),
        migrations.AddIndex(
            model_name='challengeplayerbooking',
            index=models.Index(fields=['player_id', 'booking_id'], name='cpb_player_booking'),
        ),
    ]
