# Generated by Django 5.2.10 on 2026-05-21 19:32

import core.utils
import dashboard_manage.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('working_days', models.JSONField(default=dict, validators=[dashboard_manage.validators.validate_working_days])),
                ('logo', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating_count', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('flexible_reservation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('governorate', models.PositiveSmallIntegerField(choices=[(1, 'دمشق'), (2, 'ريف دمشق'), (3, 'حمص'), (4, 'اللاذقية'), (5, 'طرطوس')])),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPriceStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('money_from_completed_owner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('money_from_completed_player', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('money_from_pending_pay_player', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('money_from_pending_pay_owner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.CreateModel(
            name='BookingNumStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('completed_num', models.PositiveSmallIntegerField(default=0)),
                ('completed_num_owner', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_completed_owner', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_pending_pay_owner', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_pending_pay_player', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_completed_player', models.PositiveSmallIntegerField(default=0)),
                ('reject_num', models.PositiveSmallIntegerField(default=0)),
                ('pending_pay_num', models.PositiveSmallIntegerField(default=0)),
                ('pay_num', models.PositiveSmallIntegerField(default=0)),
                ('pending_pay_num_owner', models.PositiveSmallIntegerField(default=0)),
                ('pending_player_num', models.PositiveSmallIntegerField(default=0)),
                ('no_Show_num', models.PositiveSmallIntegerField(default=0)),
                ('disputed_num', models.PositiveSmallIntegerField(default=0)),
                ('expired_num', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('deposit_percent', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deteted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ClubEquipmentStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_by_ower', models.PositiveSmallIntegerField(default=0)),
                ('revenue_by_owner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity_by_player', models.PositiveSmallIntegerField(default=0)),
                ('revenue_by_player', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('club_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment')),
            ],
        ),
        migrations.CreateModel(
            name='ClubOpeningTimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateField(default=django.utils.timezone.localdate)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Weekday'), (2, 'date')])),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
            options={
                'verbose_name': 'Club Pricing',
                'verbose_name_plural': 'Club Pricings',
                'db_table': 'clubs_pricing',
            },
        ),
        migrations.CreateModel(
            name='ClubStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
                ('type', models.CharField(max_length=15)),
                ('size_high', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('size_width', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_deteted', models.BooleanField(default=False)),
                ('price_first', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('price_second', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('time_interval', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
            options={
                'verbose_name': 'Pitch',
                'verbose_name_plural': 'Pitches',
                'db_table': 'pitches',
                'ordering': ['club', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClubHourlyStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.SmallIntegerField()),
                ('booked_minutes', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTypeHoure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['manager'], name='clubs_manager_6321c3_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['rating_avg'], name='clubs_rating__8a11b5_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['longitude', 'latitude'], name='clubs_longitu_86b20a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpricestatistics',
            unique_together={('club', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='bookingnumstatistics',
            unique_together={('club', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='clubequipmentstatistics',
            unique_together={('club', 'club_equipment', 'date')},
        ),
        migrations.AddIndex(
            model_name='clubpricing',
            index=models.Index(fields=['club', 'day_of_week'], name='clubs_prici_club_id_52f2de_idx'),
        ),
        migrations.AddIndex(
            model_name='clubpricing',
            index=models.Index(fields=['club', 'date'], name='clubs_prici_club_id_747fdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubequipment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deteted', False)), fields=('club', 'equipment'), name='uniq_club_equipment'),
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['club', 'is_active'], name='pitches_club_id_718654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubhourlystatistics',
            unique_together={('club', 'pitch', 'date', 'hour')},
        ),
        migrations.AddIndex(
            model_name='reservationtypehoure',
            index=models.Index(fields=['club'], name='dashboard_m_club_id_996635_idx'),
        ),
    ]
