# Generated by Django 5.2.10 on 2026-01-24 11:59

import core.utils
import dashboard_manage.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('working_days', models.JSONField(default=dict, validators=[dashboard_manage.validators.validate_working_days])),
                ('logo', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating_count', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('flexible_reservation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Weekday'), (2, 'date')])),
                ('day_of_week', models.SmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
            options={
                'verbose_name': 'Club Pricing',
                'verbose_name_plural': 'Club Pricings',
                'db_table': 'clubs_pricing',
            },
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
                ('type', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('price_first', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_second', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_interval', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
            options={
                'verbose_name': 'Pitch',
                'verbose_name_plural': 'Pitches',
                'db_table': 'pitches',
                'ordering': ['club', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReservationTypeHoure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['manager'], name='clubs_manager_6321c3_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['rating_avg'], name='clubs_rating__8a11b5_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['longitude', 'latitude'], name='clubs_longitu_86b20a_idx'),
        ),
        migrations.AddIndex(
            model_name='clubpricing',
            index=models.Index(fields=['club', 'day_of_week'], name='clubs_prici_club_id_52f2de_idx'),
        ),
        migrations.AddIndex(
            model_name='clubpricing',
            index=models.Index(fields=['club', 'date'], name='clubs_prici_club_id_747fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['club', 'is_active'], name='pitches_club_id_718654_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationtypehoure',
            index=models.Index(fields=['club'], name='dashboard_m_club_id_996635_idx'),
        ),
    ]
