# Generated by Django 5.2.10 on 2026-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='size',
        ),
        migrations.AddField(
            model_name='pitch',
            name='size_high',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitch',
            name='size_width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
