# Generated by Django 5.2.10 on 2026-02-13 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0002_alter_equipment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubequipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
