# Generated by Django 5.2.10 on 2026-01-26 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0003_alter_club_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpricing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubpricing',
            name='day_of_week',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
