# Generated by Django 5.2.10 on 2026-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0004_alter_clubpricing_date_alter_clubpricing_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
