# Generated by Django 5.2.10 on 2026-02-20 08:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0004_alter_equipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubequipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.equipment', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
