# Generated by Django 5.2.10 on 2026-02-20 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0005_clubequipment_price_alter_clubequipment_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.equipment'),
        ),
        migrations.AlterField(
            model_name='clubequipment',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
