# Generated by Django 5.2.10 on 2026-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0006_alter_clubequipment_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubequipment',
            name='is_deteted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitch',
            name='is_deteted',
            field=models.BooleanField(default=False),
        ),
    ]
