# Generated by Django 5.2.10 on 2026-02-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0007_clubequipment_is_deteted_pitch_is_deteted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubequipment',
            name='uniq_club_equipment',
        ),
        migrations.AddConstraint(
            model_name='clubequipment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deteted', False)), fields=('club', 'equipment'), name='uniq_club_equipment'),
        ),
    ]
