# Generated by Django 5.2.10 on 2026-02-28 10:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0008_remove_clubequipment_uniq_club_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingNumStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('completed_num', models.PositiveSmallIntegerField(default=0)),
                ('completed_num_owner', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_completed_owner', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_pending_pay_owner', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_pending_pay_player', models.PositiveSmallIntegerField(default=0)),
                ('canceled_num_from_completed_player', models.PositiveSmallIntegerField(default=0)),
                ('reject_num', models.PositiveSmallIntegerField(default=0)),
                ('pending_pay_num', models.PositiveSmallIntegerField(default=0)),
                ('pending_pay_num_owner', models.PositiveSmallIntegerField(default=0)),
                ('pending_player_num', models.PositiveSmallIntegerField(default=0)),
                ('no_Show_num', models.PositiveSmallIntegerField(default=0)),
                ('disputed_num', models.PositiveSmallIntegerField(default=0)),
                ('expired_num', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
            options={
                'unique_together': {('club', 'day')},
            },
        ),
        migrations.CreateModel(
            name='BookingPriceStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('money_from_completed_owner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('money_from_completed_player', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('money_from_pending_pay_player', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('money_from_pending_pay_owner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
            options={
                'unique_together': {('club', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ClubEquipmentStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity_by_ower', models.PositiveSmallIntegerField(default=0)),
                ('revenue_by_owner', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity_by_player', models.PositiveSmallIntegerField(default=0)),
                ('revenue_by_player', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('club_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.clubequipment')),
            ],
            options={
                'unique_together': {('club', 'club_equipment', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClubHourlyStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.SmallIntegerField()),
                ('booked_minutes', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.pitch')),
            ],
            options={
                'unique_together': {('club', 'pitch', 'date', 'hour')},
            },
        ),
    ]
