# Generated by Django 5.2.10 on 2026-02-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0009_bookingnumstatistics_bookingpricestatistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingnumstatistics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookingnumstatistics',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bookingpricestatistics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookingpricestatistics',
            name='updated_at',
        ),
    ]
