# Generated by Django 5.2.10 on 2026-03-06 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0010_remove_bookingnumstatistics_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
    ]
