# Generated by Django 5.2.10 on 2026-03-13 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0012_clubopeningtimehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubopeningtimehistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
