# Generated by Django 5.2.10 on 2026-03-13 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0013_alter_clubopeningtimehistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubopeningtimehistory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
