# Generated by Django 5.2.10 on 2026-04-04 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0014_alter_clubopeningtimehistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpricing',
            name='day_of_week',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
