# Generated by Django 5.2.10 on 2026-04-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0016_alter_clubequipment_price_alter_pitch_price_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubstaff',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club'),
        ),
    ]
