# Generated by Django 5.2.10 on 2026-05-02 14:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0017_alter_clubstaff_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingnumstatistics',
            name='pay_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClubDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('deposit_percent', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
            ],
        ),
    ]
