# Generated by Django 5.2.10 on 2026-05-21 19:32

import core.utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_params', models.TextField(blank=True)),
                ('request_body', models.TextField(blank=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_msg', models.TextField()),
                ('traceback', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to=core.utils.upload_to_model_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('name', models.CharField(max_length=255, verbose_name='Counterparty name')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='SYP', max_length=10)),
                ('direction', models.CharField(choices=[('+', 'Incoming'), ('-', 'Outgoing')], max_length=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='management__date_272e64_idx'), models.Index(fields=['direction'], name='management__directi_255a9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_manage.club')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['club', 'is_active'], name='management__club_id_b90240_idx'), models.Index(fields=['tag', 'is_active'], name='management__tag_id_7b8918_idx')],
            },
        ),
    ]
