# Generated by Django 5.2.10 on 2026-05-23 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_manage', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.CharField(max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='dashboard_manage.club')),
            ],
            options={
                'db_table': 'dashboard_manage_clubpayout',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['club'], name='dashboard_m_club_id_142a5f_idx'), models.Index(fields=['date'], name='dashboard_m_date_86403f_idx')],
            },
        ),
    ]
