# Generated by Django 5.2.10 on 2026-03-14 10:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_params', models.TextField(blank=True)),
                ('request_body', models.TextField(blank=True)),
                ('request_headers', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_msg', models.TextField()),
                ('traceback', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
