# Generated by Django 5.2.10 on 2026-05-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_requesterrorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('name', models.CharField(max_length=255, verbose_name='Counterparty name')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='SYP', max_length=10)),
                ('direction', models.CharField(choices=[('+', 'Incoming'), ('-', 'Outgoing')], max_length=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date'], name='management__date_272e64_idx'), models.Index(fields=['direction'], name='management__directi_255a9b_idx')],
            },
        ),
    ]
